### ISSUE TITLE
Обновить git-completion.bash

### ISSUE THREAD

**Issue by sigorilla** [tarmolov/configs#1]
Предлагаю убрать функцию `__git_ps1()`, потому что она не показывает текущих изменений или добавленных файлов. То есть например **`*`** – для изменений отслеживаемых файлов, или **`+`** – после добавления.

Вместо неё можно добавить [стандартный файл](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh) из репозитория гита.

**Comment by tarmolov** [comment]
Давай. Сделаешь pr? :)
